spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      discovery:
        enabled: true
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:${ENV_HOST}}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
  boot:
    admin:
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,activiti
      turbine:
        clusters: default
        location: turbine

