spring:
  application:
    name: @project.artifactId@
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:rabbitmq}
    port: ${RABBITMQ_DEFAULT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
