spring:
  application:
    name: spring-cloud-registry
  cloud:
    config:
      uri: ${config.server.url:http://localhost:8888}

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
