spring:
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:${ENV_HOST}}
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

---
spring:
  profiles: dev

eureka:
  server:
    enable-self-preservation: false

---
spring:
  profiles: eureka_cluster

eureka:
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:eureka}:8761/eureka/
