spring:
  application:
    name: @project.artifactId@
  cloud:
    config:
      discovery:
        enabled: true
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:rabbitmq}
    port: ${RABBITMQ_DEFAULT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}

zuul:
  ignored-services: '*'

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 100000
