server:
  port: @docker.expose@

spring:
  application:
    name: configserver
  rabbitmq:
    host: ${RABBITMQ_DEFAULT_HOST:rabbitmq}
    port: ${RABBITMQ_DEFAULT_PORT:5672}
    username: ${RABBITMQ_DEFAULT_USER:admin}
    password: ${RABBITMQ_DEFAULT_PASS:admin}
  cloud:
    config:
      server:
        git:
          username: f0rb@icloud.com
          uri: https://gitee.com/doyto/doyto-config.git

management.endpoints.web.exposure.include: "*"
management.endpoint.health.show-details: always

info:
  name: @project.artifactId@
  version: @project.version@
  date: @project.build.timestamp@

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka}:8761/eureka/
