logging:
  level:
#    com.netflix.discovery: 'OFF'
#    org.springframework.cloud: 'DEBUG'

eureka:
  client:
    serviceUrl:
      defaultZone: http://${host.master:localhost}:8761/eureka/

management:
  security:
    enabled: false

spring:
  rabbitmq:
    host: ${host.rabbit:localhost}
    port: 5672
    username: admin
    password: admin




